### PR TITLE
Rs

### PR DESCRIPTION
**Pull request by rileysiemens**
This is what I've been working on the past week:
- Filter.html is where I tested out my code.  All of it is trying to access and manipulate the restaurant data in data.csv.  It's a plain page that consists of 3 buttons.  "Chinese" returns a list of all chinese restaurants, "Burger" does the same for burger restaurants, and "Draw Header" draws in all data available for each restaurant and displays it in a way similar to how we will need to display it for our Search Results page.  Hopefully we can get away with copying and pasting into other functions as we need.

- Images folder contains all images needed for each restaurant.  Feel free to update them if you see better quality ones somewhere.  These are just small, simple pictures, most of them are of the front of the restaurant.

### CODE REVIEW

**Comment by talk2bryan** [comment]
hey Riley, do you mind putting your files in the Milestone3 directory? I think the csv and pictures should be in a resources folder, as a subfolder of Milestone3 - just so we don't have stuff everywhere

**Comment by rileysiemens** [comment]
I reorganized the hierarchy of my branch, deleted the data.csv file from the root directory and moved it into resources, but Git sees this as a conflict.  Do you know how to get around that, Bryan?

**Comment by rileysiemens** [comment]
Ok, never mind, I just added the old version of data.csv into the root and I'll delete it later.

**Comment by talk2bryan** [comment]
great!

**Pull request merged**
